[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "detect-private-key"

[[repos.hooks]]
id = "check-executables-have-shebangs"

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.1"

[[repos.hooks]]
id = "ruff-check"
args = ["--fix"]
types_or = ["python", "pyi"]

[[repos.hooks]]
id = "ruff-format"
types_or = ["python", "pyi"]
